const image = require("./static/assets/tableimg.png");
export const tableData = [
  {
    sr: 1,
    img: image,
    order: "Crispy Chicken",
    total: "$599.00",
    qty: "4",
    status: "Cancel",
  },
  {
    sr: 2,
    img: image,
    order: "Luger Burger",
    total: "$1,000.00",
    qty: "1",
    status: "Cancel",
  },
  {
    sr: 3,
    img: image,
    order: "Crispy Chicken",
    total: "$400.00",
    qty: "2",
    status: "Cancel",
  },
  {
    sr: 4,
    img: image,
    order: "Luger Burger",
    total: "$599.00",
    qty: "4",
    status: "Completed",
  },
  {
    sr: 5,
    img: image,
    order: "Crispy Chicken",
    total: "$400.00",
    qty: "4",
    status: "Cancel",
  },
  {
    sr: 6,
    img: image,
    order: "Crispy Chicken",
    total: "$599.00",
    qty: "4",
    status: "Cancel",
  },
  {
    sr: 7,
    img: image,
    order: "Luger Burger",
    total: "$599.00",
    qty: "2",
    status: "Completed",
  },
  ,
  {
    sr: 8,
    img: image,
    order: "Crispy Chicken",
    total: "$599.00",
    qty: "4",
    status: "Completed",
  },
  ,
  {
    sr: 9,
    img: image,
    order: "Luger Burger",
    total: "$68.00",
    qty: "2",
    status: "Completed",
  },
  ,
  {
    sr: 10,
    img: image,
    order: "Crispy Chicken",
    total: "$599.00",
    qty: "4",
    status: "Completed",
  },
  ,
  {
    sr: 11,
    img: image,
    order: "Luger Burger",
    total: "$68.00",
    qty: "2",
    status: "Completed",
  },
  ,
  {
    sr: 12,
    img: image,
    order: "Crispy Chicken",
    total: "$599.00",
    qty: "4",
    status: "Completed",
  },
];
